spring:
  application:
    name: ms-job
  datasource:
    url: jdbc:postgresql://postgres:5432/ms-job
    username: user
    password: password
  kafka:
    bootstrap-servers:  kafka:29092

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka