spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ms-job-application
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: kafka:29092

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka

file:
  upload-dir: /app/uploads
