spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ms-job-user
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka