spring:
  application:
    name: ms-job-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-application
          uri: lb://MS-APPLICATION
          predicates:
            - Path=/api/application/**
          filters:
            - RewritePath=/api/application/(?<segment>.*), /api/v1/application/${segment}
            - AuthenticationFilter

        - id: ms-job
          uri: lb://MS-JOB
          predicates:
            - Path=/api/job/**, /api/company/**
          filters:
            - RewritePath=/api/(?<segment1>job|company)/(?<segment2>.*), /api/v1/${segment1}/${segment2}
            - AuthenticationFilter

        - id: ms-job-auth
          uri : lb://MS-JOB-AUTH
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /api/v1/auth/${segment}

        - id: ms-user
          uri : lb://MS-USER
          predicates:
            - Path=/api/connection/**, /api/experience/**, /api/skill/**, /api/user/**
          filters:
            - RewritePath=/api/(?<segment1>connection|experience|skill|user)/(?<segment2>.*), /api/v1/${segment1}/${segment2}
            - AuthenticationFilter

        - id: ms-search
          uri: lb://MS-SEARCH
          predicates:
            - Path=/api/search/**,
          filters:
            - RewritePath=/api/search/(?<segment>.*), /api/v1/search/${segment}

  main:
    web-application-type: reactive


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8080